# Generated by Django 5.2.7 on 2025-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tenant_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
