# Generated by Django 5.2.7 on 2025-12-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_maintenancerequest_maintenance_type'),
        ('dashboard', '0002_monthlybilling'),
    ]

    operations = [
    ]
