# Generated by Django 5.2.7 on 2025-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_maintenancerequest_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
