# Generated by Django 5.2.7 on 2025-11-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_verified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
